In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
land = ""
rb = ""
data = []
ofile = open("2017.csv","r")
header = ofile.readline()
for line in ofile:
    if line[0].isdigit():
        data.append([2017,land, rb] + line.replace("\n","").split(";"))
    elif line.startswith("RB"):
        rb = line.split(" ")[1].replace("\n","").split(";")[0]
    else:
        land = line.replace("\n","").split(";")[0]
ofile.close()
        
df = pd.DataFrame(data, columns = ["year","land", "rb"] + header.replace("\n","").split(";"))

In [3]:
df

,year,land,rb,Stadt,Insgesamt,Benzin,Diesel,Gas (einschl. bivalent),Hybrid,Elektro,...,Euro 5,Euro 6,Sonstige2,Euro 1 2,Euro 2 2,Euro 3 2,Euro 4 2,Euro 5 2,Euro 6 2,Sonstige3
0,2017,BADEN-WUERTTEMBERG,STUTTGART,"08111 STUTTGART,STADT",298172,182451,111148,1893,1788,814,...,83244,71586,950,191,3968,11644,20293,40400,34048,215
1,2017,BADEN-WUERTTEMBERG,STUTTGART,08115 BOEBLINGEN,244396,155578,85499,1452,1336,474,...,70308,55635,781,273,3344,10316,18819,31203,21020,251
2,2017,BADEN-WUERTTEMBERG,STUTTGART,08116 ESSLINGEN,319920,208669,107640,1907,1301,325,...,95314,50751,1247,496,4855,14593,24567,41681,20561,430
3,2017,BADEN-WUERTTEMBERG,STUTTGART,08117 GOEPPINGEN,158197,101819,54352,1299,574,110,...,49480,21718,579,217,2571,7641,13082,21763,8677,226
4,2017,BADEN-WUERTTEMBERG,STUTTGART,08118 LUDWIGSBURG,319997,213243,102776,2228,1256,413,...,95509,46700,873,227,4549,13829,24422,40374,18801,220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396,2017,THUERINGEN,ZUSAMMEN,16073 SAALFELD-RUDOLSTADT,61213,42847,17601,552,171,14,...,19891,7208,192,80,767,2184,4065,7712,2703,42
397,2017,THUERINGEN,ZUSAMMEN,16074 SAALE-HOLZLANDKREIS,48605,33353,14461,563,200,9,...,15040,5530,140,79,656,1876,3408,6154,2213,35
398,2017,THUERINGEN,ZUSAMMEN,16075 SAALE-ORLA-KREIS,50214,34143,15474,487,83,10,...,15919,5147,146,62,648,2022,3736,6835,2123,19
399,2017,THUERINGEN,ZUSAMMEN,16076 GREIZ,60093,41998,17248,630,181,14,...,18876,6871,261,80,835,2287,3951,7368,2640,50
400,2017,THUERINGEN,ZUSAMMEN,16077 ALTENBURGER LAND,51231,38381,12212,486,109,22,...,15345,5873,247,51,511,1552,2817,5301,1925,38

In [4]:
df["Insgesamt"].head(5)

0    298172
1    244396
2    319920
3    158197
4    319997
Name: Insgesamt, dtype: object

In [5]:
df["land"].unique()

array(['BADEN-WUERTTEMBERG', 'BAYERN', 'BERLIN ', 'BRANDENBURG ',
       'BREMEN ', 'HAMBURG ', 'HESSEN ', 'MECKLENBURG-VORPOMMERN ',
       'NIEDERSACHSEN ', 'NORDRHEIN-WESTFALEN ', 'RHEINLAND-PFALZ ',
       'SAARLAND ', 'SACHSEN ', 'SACHSEN-ANHALT ', 'SCHLESWIG-HOLSTEIN ',
       'THUERINGEN '], dtype=object)

In [6]:
df["land"] = df["land"].str.strip(" ")

In [7]:
df[df["land"]=="SACHSEN-ANHALT"]

,year,land,rb,Stadt,Insgesamt,Benzin,Diesel,Gas (einschl. bivalent),Hybrid,Elektro,...,Euro 5,Euro 6,Sonstige2,Euro 1 2,Euro 2 2,Euro 3 2,Euro 4 2,Euro 5 2,Euro 6 2,Sonstige3
349,2017,SACHSEN-ANHALT,ZUSAMMEN,"15001 DESSAU-ROßLAU,STADT",41926,31335,9893,473,184,10,...,12913,4949,116,43,382,1243,2075,4353,1726,37
350,2017,SACHSEN-ANHALT,ZUSAMMEN,"15002 HALLE (SAALE),STADT",92840,69513,21767,975,487,37,...,29035,12234,202,81,690,2428,4878,9315,4253,56
351,2017,SACHSEN-ANHALT,ZUSAMMEN,"15003 MAGDEBURG, STADT",109014,79428,28111,975,402,47,...,33580,14026,550,101,885,3033,6187,12332,5376,129
352,2017,SACHSEN-ANHALT,ZUSAMMEN,15081 ALTMARKKREIS SALZWEDEL,50257,32781,16808,510,125,13,...,14195,4357,282,87,1091,2570,4383,6586,1970,74
353,2017,SACHSEN-ANHALT,ZUSAMMEN,15082 ANHALT-BITTERFELD,92073,68444,22635,686,235,24,...,27908,9941,234,119,958,2915,5243,9790,3509,49
354,2017,SACHSEN-ANHALT,ZUSAMMEN,15083 BOERDE,104142,71865,30967,1095,151,27,...,31920,10133,302,135,1452,4084,7815,13158,4141,91
355,2017,SACHSEN-ANHALT,ZUSAMMEN,15084 BURGENLANDKREIS,100738,73655,25599,1118,278,20,...,30687,10708,313,99,1066,3312,6179,11035,3802,57
356,2017,SACHSEN-ANHALT,ZUSAMMEN,15085 HARZ,121437,84362,35272,1410,283,39,...,37928,13382,336,156,1627,4868,8335,15071,5011,92
357,2017,SACHSEN-ANHALT,ZUSAMMEN,15086 JERICHOWER LAND,53633,37152,15824,453,167,7,...,15486,4931,337,99,858,2320,3866,6583,1975,72
358,2017,SACHSEN-ANHALT,ZUSAMMEN,15087 MANSFELD-SUEDHARZ,79819,57056,21902,551,254,19,...,24772,9189,277,105,865,2721,5122,9598,3396,55
359,2017,SACHSEN-ANHALT,ZUSAMMEN,15088 SAALEKREIS,111877,80207,30037,1131,425,18,...,35567,13431,420,105,1136,3676,6653,13386,4943,83
360,2017,SACHSEN-ANHALT,ZUSAMMEN,15089 SALZLANDKREIS,104809,76822,26417,1177,307,15,...,31753,11142,255,123,1061,3277,6264,11489,4099,58
361,2017,SACHSEN-ANHALT,ZUSAMMEN,15090 STENDAL,62775,42088,19915,586,150,20,...,17222,5359,393,112,1166,3190,5363,7675,2278,91
362,2017,SACHSEN-ANHALT,ZUSAMMEN,15091 WITTENBERG,74431,54865,18450,774,291,14,...,21472,7410,375,87,937,2603,4371,7773,2564,76

In [8]:
for head in header.replace("\n","").split(";")[1:]:
    df[head] = pd.to_numeric(df[head].str.replace(".", ""))

In [9]:
df["Insgesamt"]

0      298172.0
1      244396.0
2      319920.0
3      158197.0
4      319997.0
         ...
396     61213.0
397     48605.0
398     50214.0
399     60093.0
400     51231.0
Name: Insgesamt, Length: 401, dtype: float64

In [17]:
def splits(val):
    return val[:5]
    
df["kennzahl"] = df["Stadt"].apply(splits)

In [22]:
def splits2(val):
    return val[7:]
    
df["ort"] = df["Stadt"].apply(splits2)

In [19]:
df["kennzahl"]

0      08111
1      08115
2      08116
3      08117
4      08118
       ...
396    16073
397    16074
398    16075
399    16076
400    16077
Name: kennzahl, Length: 401, dtype: object

In [24]:
df["ort"]

0          STUTTGART,STADT
1               BOEBLINGEN
2                ESSLINGEN
3               GOEPPINGEN
4              LUDWIGSBURG
              ...
396    AALFELD-RUDOLSTADT
397    AALE-HOLZLANDKREIS
398       AALE-ORLA-KREIS
399                  REIZ
400       LTENBURGER LAND
Name: ort, Length: 401, dtype: object